name: Rust

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust stable
        run: |
          rustup toolchain update --no-self-update stable
          rustup default stable
          rustup component add clippy rustfmt
          rustup show

      - name: Run rustfmt
        run: cargo fmt -- --check --verbose

      - name: Run clippy
        run: cargo clippy --verbose --all --all-features -- -Dwarnings

      - name: Run build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --all --verbose
